#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "33i \\\\t\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default
sudo service nginx restart
