#!/usr/bin/env bash
# Install your load balancer

sudo apt-get -y update
sudo apt-get install -y haproxy

echo "
frontend JhoanRodriguez
    bind *:80
    mode http
    default_backend backendnodes
backend backendnodes
    balance roundrobin
    option forwardfor
    server 1590-web-01 35.196.46.151:80 check
    server 1587-web-02 34.73.33.136:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
