#!/usr/bin/env bash
#Script Case that show bad luck from china if number is 4
# Show bad luck from japan if number is 9
# Show bad luck from italy if number is 17

i=1
while [ $i -le 20 ]
do
	echo $i
	case "$i" in
	"4") echo "bad luck from China"
	    ;;
	"9") echo "bad luck from Japan"
	    ;;
	"17") echo "bad luck from Italy"
	     ;;
	 esac
	 (( i++ ))
done