#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with


cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.2/127.0.0.1/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm -rf ~/hosts.new